services:
  app:
    container_name: ${APP_NAME}_app
    restart: on-failure
    build: ./docker-compose
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
  
volumes:
  bundle_cache:
