services:
  app:
    container_name: ${APP_NAME}_app
    restart: on-failure
    build: ./docker-compose
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres@postgres/${APP_NAME}_development
      TEST_DATABASE_URL: postgresql://postgres@postgres/${APP_NAME}_test
  postgres:
    container_name: ${APP_NAME}_db
    image: postgres:13-alpine
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_DB: ${APP_NAME}_development
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker-compose/postgres:/var/lib/postgresql/data
      - ./docker-compose/db_restore:/home/db_restore
    ports:
      - "5433:5432"
volumes:
  bundle_cache:
